# Generated by Django 5.1.2 on 2024-10-21 08:18

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('name', models.CharField(max_length=50)),
                ('rollno', models.AutoField(primary_key=True, serialize=False)),
                ('classteacher', models.CharField(max_length=50)),
                ('phy_marks', models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(50)])),
                ('che_marks', models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(50)])),
                ('maths_marks', models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(50)])),
                ('total_marks', models.FloatField(editable=False)),
                ('percentage', models.FloatField(editable=False)),
            ],
        ),
    ]
