# Generated by Django 5.1.2 on 2024-10-21 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='che_pass',
            field=models.BooleanField(default=False, editable=False),
        ),
        migrations.AddField(
            model_name='student',
            name='maths_pass',
            field=models.BooleanField(default=False, editable=False),
        ),
        migrations.AddField(
            model_name='student',
            name='phy_pass',
            field=models.BooleanField(default=False, editable=False),
        ),
        migrations.AddField(
            model_name='student',
            name='result',
            field=models.BooleanField(default=False, editable=False),
        ),
    ]
