# Generated by Django 5.1.2 on 2024-10-21 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyApp', '0002_student_che_pass_student_maths_pass_student_phy_pass_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='che_pass',
            field=models.BooleanField(default=True, editable=False),
        ),
        migrations.AlterField(
            model_name='student',
            name='maths_pass',
            field=models.BooleanField(default=True, editable=False),
        ),
        migrations.AlterField(
            model_name='student',
            name='phy_pass',
            field=models.BooleanField(default=True, editable=False),
        ),
        migrations.AlterField(
            model_name='student',
            name='result',
            field=models.BooleanField(default=True, editable=False),
        ),
    ]
