# Generated by Django 5.1.2 on 2024-10-21 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyApp', '0003_alter_student_che_pass_alter_student_maths_pass_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='che_pass',
            field=models.BooleanField(editable=False),
        ),
        migrations.AlterField(
            model_name='student',
            name='maths_pass',
            field=models.BooleanField(editable=False),
        ),
        migrations.AlterField(
            model_name='student',
            name='phy_pass',
            field=models.BooleanField(editable=False),
        ),
        migrations.AlterField(
            model_name='student',
            name='result',
            field=models.BooleanField(editable=False),
        ),
    ]
