# Generated by Django 5.1.2 on 2024-10-22 05:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyApp', '0005_teacher'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='teacher_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='MyApp.teacher'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='empid',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
